<a href="https://colab.research.google.com/github/Iamnetis/UMSL-AI/blob/main/Activity_7_(My_Binary_Classification_using_NN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving pima-diabetes.csv to pima-diabetes.csv


In [ ]:
import pandas as pd
data = pd.read_csv('pima-diabetes.csv', delimiter = ',')

In [ ]:
data.head

<bound method NDFrame.head of      Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]>

In [ ]:
import numpy as np
dataset = np.loadtxt('pima-diabetes.csv', delimiter =',', skiprows = 1)

In [ ]:
print (dataset[:10])

[[6.00 148.00 72.00 35.00 0.00 33.60 0.63 50.00 1.00]
 [1.00 85.00 66.00 29.00 0.00 26.60 0.35 31.00 0.00]
 [8.00 183.00 64.00 0.00 0.00 23.30 0.67 32.00 1.00]
 [1.00 89.00 66.00 23.00 94.00 28.10 0.17 21.00 0.00]
 [0.00 137.00 40.00 35.00 168.00 43.10 2.29 33.00 1.00]
 [5.00 116.00 74.00 0.00 0.00 25.60 0.20 30.00 0.00]
 [3.00 78.00 50.00 32.00 88.00 31.00 0.25 26.00 1.00]
 [10.00 115.00 0.00 0.00 0.00 35.30 0.13 29.00 0.00]
 [2.00 197.00 70.00 45.00 543.00 30.50 0.16 53.00 1.00]
 [8.00 125.00 96.00 0.00 0.00 0.00 0.23 54.00 1.00]]


In [ ]:
print (dataset.shape)

(768, 9)


In [ ]:
np.set_printoptions(formatter={'float': '{:0.2f}'.format})

In [ ]:
X = dataset [:, :-1]
Y = dataset [:, -1]

In [ ]:
print (X.shape, Y.shape)

(768, 8) (768,)


In [ ]:
#Data Normalization
min = X.min(axis = 0)
max = X.max(axis = 0)
X = (X-min)/(max-min)
print (min)
print('/n')
print (max)

[0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.00]
/n
[1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00]


In [ ]:
print (dataset[:10])

[[6.00 148.00 72.00 35.00 0.00 33.60 0.63 50.00 1.00]
 [1.00 85.00 66.00 29.00 0.00 26.60 0.35 31.00 0.00]
 [8.00 183.00 64.00 0.00 0.00 23.30 0.67 32.00 1.00]
 [1.00 89.00 66.00 23.00 94.00 28.10 0.17 21.00 0.00]
 [0.00 137.00 40.00 35.00 168.00 43.10 2.29 33.00 1.00]
 [5.00 116.00 74.00 0.00 0.00 25.60 0.20 30.00 0.00]
 [3.00 78.00 50.00 32.00 88.00 31.00 0.25 26.00 1.00]
 [10.00 115.00 0.00 0.00 0.00 35.30 0.13 29.00 0.00]
 [2.00 197.00 70.00 45.00 543.00 30.50 0.16 53.00 1.00]
 [8.00 125.00 96.00 0.00 0.00 0.00 0.23 54.00 1.00]]


In [ ]:
# Building NN...
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(8, input_dim = len(X[0, :]), activation = 'relu')) # relu is a comman used non linear activation function
model.add(Dense(4, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid')) # Sigmoid activation function is always used to do predict between 0-1 

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 5         
Total params: 113
Trainable params: 113
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss = 'binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])

In [ ]:
model.fit(x = X, y = Y, epochs= 256, verbose = 1)

Epoch 1/256
24/24 [==============================] - 0s 697us/step - loss: 0.4872 - accuracy: 0.7734
Epoch 2/256
24/24 [==============================] - 0s 1ms/step - loss: 0.4826 - accuracy: 0.7760
Epoch 3/256
24/24 [==============================] - 0s 663us/step - loss: 0.4791 - accuracy: 0.7682
Epoch 4/256
24/24 [==============================] - 0s 618us/step - loss: 0.4845 - accuracy: 0.7669
Epoch 5/256
24/24 [==============================] - 0s 637us/step - loss: 0.4911 - accuracy: 0.7773
Epoch 6/256
24/24 [==============================] - 0s 690us/step - loss: 0.4829 - accuracy: 0.7695
Epoch 7/256
24/24 [==============================] - 0s 694us/step - loss: 0.4800 - accuracy: 0.7812
Epoch 8/256
24/24 [==============================] - 0s 662us/step - loss: 0.4842 - accuracy: 0.7734
Epoch 9/256
24/24 [==============================] - 0s 673us/step - loss: 0.4811 - accuracy: 0.7799
Epoch 10/256
24/24 [==============================] - 0s 648us/step - loss: 0.4772 - accuracy

In [ ]:
# Evaluating the model using accuracy, precision and recall
prediction = model.predict(X)
print (prediction[:5].T)

[[0.86 0.09 0.89 0.10 0.76]]


In [ ]:
print (Y[:20])

[1.00 0.00 1.00 0.00 1.00 0.00 1.00 0.00 1.00 1.00 0.00 1.00 0.00 1.00
 1.00 1.00 1.00 1.00 0.00 1.00]


In [ ]:
a = prediction.sum()
b = Y.sum()
print (a)
print(b)
print (b/a *100)

283.2664
268.0
94.61058968185232


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
my_accuracy = accuracy_score(Y, prediction.round()) #Accuracy
print(my_accuracy * 100)

79.296875


In [ ]:
len(Y)

768

In [ ]:
Y.sum()

268.0

In [ ]:
268/768 * 100 # Positive and rest are Negative (bad)

34.89583333333333

In [ ]:
#Precision
my_percision = precision_score(Y, prediction.round())
print (my_percision)

0.7261410788381742


In [ ]:
#recall
my_recall = recall_score(Y, prediction.round())
print (my_recall)

0.6529850746268657


In [ ]:
print (768-268)

500


In [ ]:
# Baseline accuracy (ratio of larger set /  total data points)
#larger set vaneko Y value ko sum (Y.sum()) ra total dataset substract garera nikalne ho...
print ('The baseline accuracy is: ', 500/768 * 100)

The baseline accuracy is:  65.10416666666666
