<a href="https://colab.research.google.com/github/Iamnetis/UMSL-AI/blob/main/Activity_11_(Overfitting_vs_Generalization).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload ()


In [ ]:
import pandas as pd
dataset = pd.read_csv('pima-diabetes.csv')
dataset.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
import numpy as np
dataset = np.genfromtxt('pima-diabetes.csv', delimiter =',', skip_header = True)

In [ ]:
np.set_printoptions(formatter={'float': '{:0.4f}'.format})

In [ ]:
print(dataset.shape)

(768, 9)


In [ ]:
import random
np.random.shuffle(dataset)

In [ ]:
# Split into training and validation, 30% validation set and 70% training 
index_30percent = int(0.3 * len(dataset[:, 0]))
print(index_30percent)
# Validation Sets (30%)
XVALID = dataset[:index_30percent, 0:8]
YVALID = dataset[:index_30percent, 8 ]

# Training sets (70%)
XTRAIN = dataset[index_30percent:, 0:8]
YTRAIN = dataset[index_30percent:, 8]

230


In [ ]:
print(XVALID[:30])
print ('\n')
print(YVALID[:30])

[[3.0000 129.0000 92.0000 49.0000 155.0000 36.4000 0.9680 32.0000]
 [6.0000 125.0000 76.0000 0.0000 0.0000 33.8000 0.1210 54.0000]
 [3.0000 191.0000 68.0000 15.0000 130.0000 30.9000 0.2990 34.0000]
 [1.0000 189.0000 60.0000 23.0000 846.0000 30.1000 0.3980 59.0000]
 [1.0000 87.0000 68.0000 34.0000 77.0000 37.6000 0.4010 24.0000]
 [7.0000 142.0000 60.0000 33.0000 190.0000 28.8000 0.6870 61.0000]
 [0.0000 108.0000 68.0000 20.0000 0.0000 27.3000 0.7870 32.0000]
 [7.0000 196.0000 90.0000 0.0000 0.0000 39.8000 0.4510 41.0000]
 [0.0000 78.0000 88.0000 29.0000 40.0000 36.9000 0.4340 21.0000]
 [1.0000 102.0000 74.0000 0.0000 0.0000 39.5000 0.2930 42.0000]
 [2.0000 83.0000 65.0000 28.0000 66.0000 36.8000 0.6290 24.0000]
 [2.0000 128.0000 64.0000 42.0000 0.0000 40.0000 1.1010 24.0000]
 [8.0000 186.0000 90.0000 35.0000 225.0000 34.5000 0.4230 37.0000]
 [6.0000 99.0000 60.0000 19.0000 54.0000 26.9000 0.4970 32.0000]
 [4.0000 131.0000 68.0000 21.0000 166.0000 33.1000 0.1600 28.0000]
 [3.0000 108.000

In [ ]:
print (XVALID.shape, YVALID.shape)

(230, 8) (230,)


In [ ]:
print(XTRAIN[:30])
print ('\n')
print(YTRAIN[:30])

[[2.0000 82.0000 52.0000 22.0000 115.0000 28.5000 1.6990 25.0000]
 [2.0000 146.0000 0.0000 0.0000 0.0000 27.5000 0.2400 28.0000]
 [1.0000 71.0000 48.0000 18.0000 76.0000 20.4000 0.3230 22.0000]
 [6.0000 183.0000 94.0000 0.0000 0.0000 40.8000 1.4610 45.0000]
 [6.0000 165.0000 68.0000 26.0000 168.0000 33.6000 0.6310 49.0000]
 [1.0000 115.0000 70.0000 30.0000 96.0000 34.6000 0.5290 32.0000]
 [2.0000 99.0000 70.0000 16.0000 44.0000 20.4000 0.2350 27.0000]
 [4.0000 76.0000 62.0000 0.0000 0.0000 34.0000 0.3910 25.0000]
 [3.0000 173.0000 82.0000 48.0000 465.0000 38.4000 2.1370 25.0000]
 [0.0000 198.0000 66.0000 32.0000 274.0000 41.3000 0.5020 28.0000]
 [10.0000 168.0000 74.0000 0.0000 0.0000 38.0000 0.5370 34.0000]
 [4.0000 173.0000 70.0000 14.0000 168.0000 29.7000 0.3610 33.0000]
 [5.0000 99.0000 74.0000 27.0000 0.0000 29.0000 0.2030 32.0000]
 [6.0000 105.0000 70.0000 32.0000 68.0000 30.8000 0.1220 37.0000]
 [0.0000 86.0000 68.0000 32.0000 0.0000 35.8000 0.2380 25.0000]
 [5.0000 96.0000 74.0

In [ ]:
print (XTRAIN.shape, YTRAIN.shape)

(538, 8) (538,)


In [ ]:
# Building Neural Network...
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(30, input_dim = 8, activation = 'relu'))
model.add(Dense(20, activation = 'relu'))
model.add(Dense(15, activation = 'relu'))
model.add(Dense(7, activation = 'relu'))
model.add(Dense(4, activation = 'relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 30)                270       
_________________________________________________________________
dense_1 (Dense)              (None, 20)                620       
_________________________________________________________________
dense_2 (Dense)              (None, 15)                315       
_________________________________________________________________
dense_3 (Dense)              (None, 7)                 112       
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 32        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 5         
Total params: 1,354
Trainable params: 1,354
Non-trainable params: 0
______________________________________________________

In [ ]:
model.compile(loss ='binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])

In [ ]:
model.fit(XTRAIN, YTRAIN, epochs= 60, verbose = 1)

Epoch 1/60
17/17 [==============================] - 0s 4ms/step - loss: 2.4296 - accuracy: 0.3476
Epoch 2/60
17/17 [==============================] - 0s 4ms/step - loss: 0.7423 - accuracy: 0.5297
Epoch 3/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6669 - accuracy: 0.6431
Epoch 4/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6596 - accuracy: 0.6450
Epoch 5/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6474 - accuracy: 0.6617
Epoch 6/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6312 - accuracy: 0.6673
Epoch 7/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6269 - accuracy: 0.6636
Epoch 8/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6180 - accuracy: 0.6840
Epoch 9/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6092 - accuracy: 0.6710
Epoch 10/60
17/17 [==============================] - 0s 3ms/step - loss: 0.6061 - accuracy: 0.6729
Epoch 11/60
17/17 [

In [ ]:
# Evaluate on the training set (should deliver high accuracy)
P = model.predict(XTRAIN)
accuracy = model.evaluate(XTRAIN, YTRAIN)

17/17 [==============================] - 0s 2ms/step - loss: 0.3258 - accuracy: 0.8587


In [ ]:
#Evaluate on the validation set
P = model.predict(XVALID)
accuracy = model.evaluate(XVALID, YVALID)

8/8 [==============================] - 0s 2ms/step - loss: 1.1669 - accuracy: 0.7000
