<a href="https://colab.research.google.com/github/Iamnetis/UMSL-AI/blob/main/My_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving lung_cancer_examples.csv to lung_cancer_examples.csv


In [ ]:
import pandas as pd
data = pd.read_csv('lung_cancer_examples.csv', delimiter= ',')
data.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [ ]:
import numpy as np
dataset = np.genfromtxt('lung_cancer_examples.csv', delimiter =',', skip_header=True, usecols = (2, 3, 6))

In [ ]:
np.set_printoptions(precision = 2) # does not work for too wide array
np.set_printoptions(formatter = {'float': '{: 0.1f}'.format})

In [ ]:
print (dataset.shape)

(59, 3)


In [ ]:
print (dataset[: 20])

[[ 35.0  3.0  1.0]
 [ 27.0  20.0  1.0]
 [ 30.0  0.0  0.0]
 [ 28.0  0.0  0.0]
 [ 68.0  4.0  1.0]
 [ 34.0  0.0  0.0]
 [ 58.0  15.0  0.0]
 [ 22.0  12.0  0.0]
 [ 45.0  2.0  0.0]
 [ 52.0  18.0  1.0]
 [ 33.0  4.0  0.0]
 [ 18.0  10.0  0.0]
 [ 25.0  2.0  0.0]
 [ 28.0  20.0  1.0]
 [ 34.0  25.0  1.0]
 [ 39.0  18.0  0.0]
 [ 42.0  22.0  1.0]
 [ 19.0  12.0  0.0]
 [ 62.0  5.0  1.0]
 [ 73.0  10.0  1.0]]


In [ ]:
import plotly.express as px
import pandas as pd

d = {'Age': dataset[:,0], 'Smokes': dataset[:, 1], 'Result': dataset[:, 2]}

In [ ]:
print (d)

{'Age': array([ 35.0,  27.0,  30.0,  28.0,  68.0,  34.0,  58.0,  22.0,  45.0,
        52.0,  33.0,  18.0,  25.0,  28.0,  34.0,  39.0,  42.0,  19.0,
        62.0,  73.0,  55.0,  33.0,  22.0,  44.0,  77.0,  21.0,  37.0,
        34.0,  55.0,  40.0,  36.0,  56.0,  47.0,  62.0,  26.0,  25.0,
        59.0,  62.0,  33.0,  37.0,  50.0,  47.0,  69.0,  63.0,  39.0,
        21.0,  31.0,  28.0,  53.0,  62.0,  42.0,  44.0,  26.0,  35.0,
        26.0,  77.0,  75.0,  43.0,  51.0]), 'Smokes': array([ 3.0,  20.0,  0.0,  0.0,  4.0,  0.0,  15.0,  12.0,  2.0,  18.0,
        4.0,  10.0,  2.0,  20.0,  25.0,  18.0,  22.0,  12.0,  5.0,  10.0,
        15.0,  8.0,  20.0,  5.0,  3.0,  20.0,  15.0,  12.0,  20.0,  20.0,
        13.0,  20.0,  15.0,  25.0,  10.0,  20.0,  20.0,  15.0,  25.0,
        10.0,  20.0,  12.0,  20.0,  20.0,  15.0,  20.0,  20.0,  10.0,
        20.0,  20.0,  12.0,  30.0,  34.0,  20.0,  13.0,  20.0,  15.0,
        30.0,  25.0]), 'Result': array([ 1.0,  1.0,  0.0,  0.0,  1.0,  0.0,  0.0,  0.0,  

In [ ]:
df = pd.DataFrame(data=d)

fig = px.scatter_3d(df,
                    x = 'Age',
                    y = 'Smokes',
                    z = 'Result', opacity = 0.4)

fig.show()

In [ ]:
X = dataset[:, :-1]
Y = dataset[:, -1]

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(1, input_dim = 2, activation='sigmoid'))

In [ ]:
model.compile(loss='binary_crossentropy', optimizer = 'rmsprop', metrics=['accuracy'])
model.fit(X, Y, epochs = 256, verbose = 1)

Epoch 1/256
2/2 [==============================] - 0s 3ms/step - loss: 24.7494 - accuracy: 0.4746
Epoch 2/256
2/2 [==============================] - 0s 2ms/step - loss: 24.6295 - accuracy: 0.4746
Epoch 3/256
2/2 [==============================] - 0s 2ms/step - loss: 24.5488 - accuracy: 0.4746
Epoch 4/256
2/2 [==============================] - 0s 2ms/step - loss: 24.4793 - accuracy: 0.4746
Epoch 5/256
2/2 [==============================] - 0s 2ms/step - loss: 24.4150 - accuracy: 0.4746
Epoch 6/256
2/2 [==============================] - 0s 2ms/step - loss: 24.3568 - accuracy: 0.4746
Epoch 7/256
2/2 [==============================] - 0s 2ms/step - loss: 24.3005 - accuracy: 0.4746
Epoch 8/256
2/2 [==============================] - 0s 2ms/step - loss: 24.2452 - accuracy: 0.4746
Epoch 9/256
2/2 [==============================] - 0s 1ms/step - loss: 24.1919 - accuracy: 0.4746
Epoch 10/256
2/2 [==============================] - 0s 2ms/step - loss: 24.1413 - accuracy: 0.4746
Epoch 11/256
2/2 [=

In [ ]:
print ('True Validation Data:')
print(Y[:10])
prediction = model.predict(X)
print ('Prediction:')
print(prediction[0:10].T)

True Validation Data:
[ 1.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0]
Prediction:
[[ 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0]]


No, I dont think they are correct. I have to learn more for make accuracy good.