<a href="https://colab.research.google.com/github/Iamnetis/UMSL-AI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,2,3]) # Rank 1 array
print(type(a), a.shape, a[0], a[1], a[2]) #a.shape tells that length of an array !!
a[0] = 7
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[7 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]]) #rank 2
print (b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [ ]:
print (b.shape)
print (b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [ ]:
a = np.zeros((2,3)) #creates an array of all zeros
print (a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((1,2,5,6,7)) #creates an array of all ones
print (b.shape)

(1, 2, 5, 6, 7)


In [ ]:
c = np.full((2,3), 8) #creates a 2x3 matrix and fill up with all 8
print (c)
type(c)

[[8 8 8]
 [8 8 8]]


numpy.ndarray

In [ ]:
d = np.eye(3) #create a 2x2 identity matrix
print (d)
type(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


numpy.ndarray

In [ ]:
e = np.random.random((2,2)) * 100 #create an array filled with random values !! 
print (e)

[[ 4.40488623  7.57711228]
 [ 5.82045609 47.19709224]]


# Array Indexing 



* Numpy offers several ways to index into arrays..
* **Slicing:** Similar to python lists, numpy arrays can be sliced...
* Since arrays may be multidimensional, ypu must specify a slice for each dimension of the array.



In [ ]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print ((a, a.shape))
print ('\n' * 2)
#Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2 

b = a[:2, 1:3]
print (b, b.shape)

(array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), (3, 4))



[[2 3]
 [6 7]] (2, 2)


A Slice of an array is a view into the same data, so modify the proginal array....

In [ ]:
b [0,0] = 77 
print (a)

[[ 1 77 77  4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


how can we make a copy of an array

In [ ]:
c = np.copy(a)
c [0,0] = 100
print(c)
print ('\n')
print(a)

[[100  77  77   4]
 [  5   6  77   8]
 [  9  10  11  12]]


[[ 1 77 77  4]
 [ 5  6 77  8]
 [ 9 10 11 12]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (a, a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [ ]:
row_r1 = a[1,:] #Rank 1 view of the second row a 
row_r2 = a[1:2, :] #Rank 2 view of the second row a 
row_r3 = a [[1], : ] #Rank 2 view of the second row a 

print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)
print (row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


*** *italicized text*Integer array indexing***

When you index into numpy arrays using slicing the resulting array view will alwyas be a subarray of the originalarray, In contrast, integet array indexing allows you to construct arbitrary arrays using the data from another array. 

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print ('a =')
print (a)

a =
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#An example of integer array indexing, The returning array will have shape(2,)

print ('=>')

print (a[[0,1], [0,1]])

=>
[1 4]


In [ ]:
print ('=>')

print (a[[0,1,2], [0, 1, 0]])

=>
[1 4 5]


In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9], [10, 11, 12]])
print (a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([0, 2, 0, 1])
print (b)

[0 2 0 1]


In [ ]:
print (np.arange(4))
print ('\n')
print (a[np.arange(4), b ] )

[0 1 2 3]


[ 1  6  7 11]


In [ ]:
a [np.arange(4), b] += 10
print (a) 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean Array Indexing**

Boolean array indexing lets you pick out arbitrary elements of an array. frequently this type of indexing is used to select the elements of an array that satisfy some condition. Eg...

In [ ]:
a = np.array([[1,2], [3,4], [5,6]])
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
bool_idx = (a > 2)

print (bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
print (a[bool_idx])

[3 4 5 6]


In [ ]:
print (a[a>2])

[3 4 5 6]


**Datatypes**



* Every numpy array is a grid of elements of the **same type** (unlike a Python list)
* Numpy Provides a large set of numeric datatypes that you can use to construct arrays
* Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype...



In [ ]:
x = np.array([1,2])
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype= np.int32)

print (x.dtype, y.dtype, z.dtype)

int64 float64 int32


**Array Math**



* Basic mathematical functions operate elementwise on arrays
* These are available as both (a) operator everloads, and (b) Functions in the numpy module



In [ ]:
x = np.array([[1,2], [3,4]], dtype = np.float64)
y = np.array([[5,6], [7,8]], dtype = np.float64)

print (x + y)
print ('\n')
print (np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


[[ 6.  8.]
 [10. 12.]]


In [ ]:
print (x - y)
print ('\n')
print (np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


[[-4. -4.]
 [-4. -4.]]


In [ ]:
print (x * y)
print ('\n')
print (np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


[[ 5. 12.]
 [21. 32.]]


In [ ]:
print (x / y)
print ('\n')
print (np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print (np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
v = np.array([9,10])
m = np.array ([11,12])

#Inner Product of vectors
print (v.dot(m))
print ('\n')
print (np.dot(v,m))

219


219


In [ ]:
x = np.array([[1,2], [3,4]])

#Matrix / vector product; both produce the rank 1 array

print (x.dot(v))
print (np.dot(x,v))

[29 67]
[29 67]


In [ ]:
y = np.array([[5,6], [7,8]])
#matrix / matrix product; both produce the rank 2 array
print (x * y)

print ('\n')

print (np.dot(x,y))

[[ 5 12]
 [21 32]]


[[19 22]
 [43 50]]


In [ ]:
import numpy as np
x = np.array([[1,2], [3,4]])

print ('x =')
print (x)
print ('sum =')
print (np.sum(x))
print ('sum alone axis 0 =')
print (np.sum(x, axis=0))
print ('sum alone axis 1 = ')
print (np.sum(x, axis = 1))

x =
[[1 2]
 [3 4]]
sum =
10
sum alone axis 0 =
[4 6]
sum alone axis 1 = 
[3 7]


In [ ]:
print (x)
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
x = np.array([[1,2], [3,4]])
print (x.shape)

y = np.reshape(x, (1,4))
print (y.shape)
print (y)

(2, 2)
(1, 4)
[[1 2 3 4]]


In [ ]:
import numpy as np


x: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
v: [1 0 1]


In [ ]:
for i in range(4):
    x[i, :] = x[i, :] + v
print (x)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
vv = np.tile(v, (4,1))
print (vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv
print (y)

[[ 3  2  5]
 [ 6  5  8]
 [ 9  8 11]
 [12 11 14]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = x + v

print (x)
print ('')
print (v)
print ('')
print (y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# Broadcasting !!

In [ ]:
#Example 1
a = np.array([1.0, 2.0, 3.0])
b = 2.0

print (a * b)

SyntaxError: ignored

In [ ]:
x = np.arange(4)
y = np.ones(5)
print (x, x.shape)
print (y, y.shape)

[0 1 2 3] (4,)
[1. 1. 1. 1. 1.] (5,)


In [ ]:
print ((x +y).shape)

In [ ]:
#Example 2
xx = x.reshape(4,1)
print(xx, xx.shape)
print ('\n')
print (y, y.shape)

[[0]
 [1]
 [2]
 [3]] (4, 1)


[1. 1. 1. 1. 1.] (5,)


In [ ]:
print ((xx + y).shape)

(4, 5)


In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

print (a, a.shape)
print (b, b.shape)

[ 0. 10. 20. 30.] (4,)
[1. 2. 3.] (3,)


In [ ]:
print (a * b.reshape(3,1))

[[ 0. 10. 20. 30.]
 [ 0. 20. 40. 60.]
 [ 0. 30. 60. 90.]]
